config/routes.rb
# matches subdomains
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

# matches blank subdomains
class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  constraints(SubdomainPresent) do
    root 'projects#index', as: :subdomain_root
    devise_for :users
    resources :users, only: :index
    resources :projects, except: [:show, :destroy]
  end
  
  constraints(SubdomainBlank) do
    root 'welcome#index'
    resources :accounts, only: [:new, :create]
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  RESTRICTED_SUBDOMAINS = %w(www)

  belongs_to :owner, class_name: 'User'

  validates :owner, presence: true
  validates :subdomain, presence: true,
                        uniqueness: { case_sensitive: false },
                        format: { with: /\A[\w\-]+\Z/i,
                                  message: 'contains invalid characters' },
                        exclusion: { in: RESTRICTED_SUBDOMAINS,
                                     message: 'restricted' }

  accepts_nested_attributes_for :owner

  before_validation :downcase_subdomain

  private

  def downcase_subdomain
    self.subdomain = subdomain.try(:downcase)
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :client, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :invitable, :database_authenticatable, :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:new, :create]

  def new
    @account = Account.new
    @account.build_owner
  end

  def create
    @account = Account.new(account_params)
    if @account.valid?
      Apartment::Tenant.create(@account.subdomain)
      Apartment::Tenant.switch!(@account.subdomain)
      @account.save
      redirect_to new_user_session_url(subdomain: @account.subdomain)
    else
      render action: 'new'
    end
  end

  private

  def account_params
    params.require(:account).permit(:subdomain, owner_attributes:
      [:name, :email, :password, :password_confirmation])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :load_schema, :authenticate_user!, :set_mailer_host
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:accept_invitation).concat([:name])
  end

  private

  def load_schema
    Apartment::Tenant.switch!('public')
    return unless request.subdomain.present?

    account = Account.find_by(subdomain: request.subdomain)
    if account
      Apartment::Tenant.switch!(request.subdomain)
    else
      redirect_to root_url(subdomain: false)
    end
  end

  def current_account
    @current_account ||= Account.find_by(subdomain: request.subdomain)
  end
  helper_method :current_account

  def set_mailer_host
    subdomain = current_account ? "#{current_account.subdomain}" : ""
   ActionMailer::Base.default_url_options[:host] = "#{subdomain}.lvh.me:3000" 
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  def after_invite_path_for(resource)
    users_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path, notice: 'Project created!'
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to root_path, notice: 'Project updated!'
    else
      render :edit
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :client, :archived)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_user!, only: :index

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
# flash messages
module LayoutHelper
  def flash_messages(opts = {})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, msg, id: "flash_#{name}")
      end
    end
  end

  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end
end

app/helpers/user_helper.rb
module UserHelper
  def user_status(user)
    if current_account.owner == user || user.invitation_accepted?
      content_tag(:span, '', class: 'glyphicon glyphicon-ok color-success')
    else
      'Invitation Pending'
    end
  end
end

app/views/accounts/new.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
	<div class="panel-body">
		<h2>Create an Account</h2>

		<%= simple_form_for @account do |f| %>

			<%= f.fields_for :owner do |o| %>
				<%= o.input :name %>
				<%= o.input :email %>
				<%= o.input :password %>
				<%= o.input :password_confirmation %>
			<% end %>

			<%= f.input :subdomain do %>
				<div class="input-group">
					<%= f.input_field :subdomain, class: 'form-control' %>
					<span class="input-group-addon">.timetracker.dev</span>
				</div>
			<% end %>
			<%= f.button :submit, class: 'btn-primary' %>
		<% end %>
	</div>
</div>

app/views/layouts/_header.html.erb
<header class="container">
	<nav class="navbar navbar-default">
		<div class="navbar-header">
			<%= link_to 'Time Tracker', root_path, class: 'navbar-brand' %>
		</div>
		<% if user_signed_in? %>
			<div class="pull-right right-buttons">
					<%= link_to 'Sign out', destroy_user_session_path, method: 'delete',
					                          class: 'btn btn-default navbar-btn' %>
			</div>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'New Project', new_project_path %></li>
				<li><%= link_to 'Users', users_path %></li>
			</ul>
		<% end %>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Time Tracker</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	<div class="container">
		<%= flash_messages if show_layout_flash? %>

		<div class="row">
			<%= yield %>
		</div>
	</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(@project,
					wrapper_mappings: { boolean: :vertical_boolean }) do |f| %>
	<%= f.input :name %>
	<%= f.input :client %>

	<% if @project.persisted? %>
		<%= f.input :archived, as: :boolean %>
	<% end %>

	<%= f.button :submit, class: 'btn-primary' %>

<% end %>

app/views/projects/edit.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
	<div class="panel-body">
		<h2>Update Project</h2>

		<%= render 'form' %>
	</div>
</div>

app/views/projects/index.html.erb
<div class="col-md-12">
	<% @projects.each do |project| %>
		<h3>
			<%= project.name %>
			<small><%= project.client %></small>
			<div class="pull-right">
				<%= link_to edit_project_path(project), class: 'icon-link' do %>
					<small><i class="glyphicon glyphicon-cog"></i></small>
				<% end %>
				<small><i class="glyphicon glyphicon-plus-sign"></i></small>
			</div>
		</h3>

		<ul class="list-group">
			<li class="list-group-item">No entries yet!</li>
		</ul>

	<% end %>
</div>

app/views/projects/new.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
	<div class="panel-body">
		<h2>New Project</h2>

		<%= render 'form' %>
	</div>
</div>

app/views/users/index.html.erb
<div class="col-md-8 col-md-offset-2">
	<h2>Authorized Users</h2>
	<div class="panel panel-default">
		<div class="panel-body">
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Name</th>
						<th>Email</th>
						<th>Status</th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
						<tr>
							<td><%= user.name %></td>
							<td><%= user.email %></td>
							<td><%= user_status(user) %></td>
						</tr>
					<% end %>
				</tbody>
			</table>

			<h3 class="extra-margin-top">Invite User</h3>

			<%= simple_form_for(User.new, url: user_invitation_path,
			                    html: { class: 'form-inline' }) do |f| %>
				<%= f.input :email, placeholder: 'Email', label: false %>
				<%= f.button :submit, 'Invite User', class: 'btn-primary' %>
			<% end %>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<div class="col-md-12">
	<div class="jumbotron">
		<h1>Time Tracker</h1>
		<p>Track your time with the most awesome time tracking app ever.</p>
		<p>
			<%= link_to 'Create Account', new_account_path, class: 'btn btn-primary btn-lg' %>
		</p>
	</div>
</div>